### YamlMime:Landing
title: Docker en la documentación de Azure
summary: Docker es una conocida plataforma de creación de imágenes y administración de contenedores que le permite trabajar rápidamente con contenedores en Linux y Windows. Aprenda a sacar el máximo partido a Docker en Azure.
metadata:
  title: Docker en la documentación de Azure
  description: Docker es una conocida plataforma de creación de imágenes y administración de contenedores que le permite trabajar rápidamente con contenedores en Linux y Windows.
  services: multiple
  ms.service: multiple
  ms.topic: landing-page
  author: georgewallace
  ms.author: gwallace
  ms.date: 03/08/2020
  ms.openlocfilehash: 700c5b1e113de32b80b3d716db915836049128ec
  ms.sourcegitcommit: 829d951d5c90442a38012daaf77e86046018e5b9
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 10/09/2020
  ms.locfileid: "89470126"
landingContent:
- title: Implementación de Docker en Azure
  linkLists:
  - linkListType: overview
    links:
    - text: Implementación de Docker en la plantilla de inicio rápido de Ubuntu
      url: https://azure.microsoft.com/resources/templates/docker-simple-on-ubuntu/
- title: Primeros pasos
  linkLists:
  - linkListType: tutorial
    links:
    - text: Ejecución de una aplicación web Python (Django) con PostgreSQL en Azure App Service
      url: ../app-service/tutorial-python-postgresql-app.md
    - text: Creación de una infraestructura de desarrollo en una máquina virtual Linux en Azure con Jenkins, GitHub y Docker
      url: /azure/developer/jenkins/pipeline-with-github-and-docker
- title: Recursos
  linkLists:
  - linkListType: reference
    links:
    - text: Sitio de Azure de Docker
      url: https://docs.docker.com/docker-for-azure/why/
    - text: Controlador de Azure de Docker
      url: https://docs.docker.com/machine/drivers/azure/
    - text: Más información acerca de Docker
      url: https://docker.com
