- name: "Documentación de los roles de Azure\_AD"
  href: index.yml
- name: Información general
  items:
    - name: Roles de Azure AD
      href: custom-overview.md
- name: Guías de inicio rápido
  items:
    - name: Creación de registros de aplicaciones ilimitadas
      href: quickstart-app-registration-limits.md
- name: Tutoriales
  items:
    - name: Creación de un grupo dinámico
      href: ../enterprise-users/users-revoke-access.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
- name: Conceptos
  expanded: true
  items:
    - name: Delegación de roles de administrador de Azure AD
      href: concept-delegation.md
    - name: Comparación de permisos predeterminados de usuario
      href: ../fundamentals/users-default-permissions.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: Comparación de roles de Azure y Azure AD
      href: ../../role-based-access-control/rbac-and-directory-admin-roles.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: "Descripción de las unidades administrativas de Azure\_AD"
      href: administrative-units.md
- name: Guías paso a paso
  expanded: true
  items:
    - name: Usuarios y roles
      items:
        - name: Asignación de usuarios a roles de administración
          href: ../fundamentals/active-directory-users-assign-role-azure-portal.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
        - name: Revocación del acceso de un usuario
          href: ../enterprise-users/users-revoke-access.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
        - name: Asignación de roles a usuarios invitados
          href: ../b2b/add-guest-to-role.md?context=%2fazure/active-directory/roles/context/ugr-context
        - name: Restricción del acceso a usuarios invitados
          href: ../enterprise-users/users-restrict-guest-permissions.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
        - name: Grupos dinámicos e invitados
          href: ../b2b/use-dynamic-groups.md?context=%2fazure/active-directory/roles/context/ugr-context
    - name: Roles y permisos
      expanded: true
      items:
        - name: Roles y permisos
          href: permissions-reference.md
        - name: Visualización y asignación de roles
          href: manage-roles-portal.md
        - name: Delegación de Mi personal
          href: my-staff-configure.md
    - name: Roles personalizados
      expanded: true
      items:
        - name: Introducción a los roles personalizados
          href: custom-overview.md
        - name: Crear un rol personalizado
          href: custom-create.md
        - name: Visualización de las asignaciones de roles personalizados
          href: custom-view-assignments.md
        - name: Asignación de roles personalizados en Azure Portal
          href: ../fundamentals/active-directory-users-assign-role-azure-portal.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
        - name: Asignación de roles personalizados en PowerShell
          href: custom-assign-powershell.md
        - name: Asignación de roles personalizados para aplicaciones empresariales
          href: custom-enterprise-apps.md
        - name: Permisos de roles personalizados
          items:
            - name: Permisos del registro de aplicaciones
              href: custom-available-permissions.md
            - name: Permisos de aplicaciones empresariales
              href: custom-enterprise-app-permissions.md
            - name: Permisos para el consentimiento de aplicaciones
              href: custom-consent-permissions.md
        - name: Delegación del rol de administrador de aplicaciones
          href: delegate-app-roles.md
    - name: Asignación de roles a grupos
      items:
        - name: Versión preliminar de la asignación de roles basada en grupo
          href: groups-concept.md
        - name: Creación de un grupo al que se pueden asignar roles
          href: groups-create-eligible.md
        - name: Asignación de roles a un grupo
          href: groups-assign-role.md
        - name: Eliminación de asignaciones de roles de un grupo
          href: groups-remove-assignment.md
        - name: Visualización de las asignaciones de roles de un grupo
          href: groups-view-assignments.md
        - name: Hacer que un grupo sea válido para un rol en PIM
          href: groups-pim-eligible.md
        - name: Preguntas más frecuentes y solución de problemas
          href: groups-faq-troubleshooting.md
    - name: Protección de roles
      items:
        - name: Planeamiento de la seguridad de rol
          href: security-planning.md
        - name: Creación de cuentas de emergencia
          href: security-emergency-access.md
    - name: Unidades administrativas
      items:
        - name: Introducción a las unidades administrativas
          href: administrative-units.md
        - name: Adición y administración
          href: admin-units-manage.md
        - name: Adición y administración de usuarios
          href: admin-units-add-manage-users.md
        - name: Agregar y administrar grupos
          href: admin-units-add-manage-groups.md
        - name: Asignación de un rol con ámbito
          href: admin-units-assign-roles.md
        - name: Preguntas más frecuentes y solución de problemas
          href: admin-units-faq-troubleshoot.md
    - name: Solución de problemas
      items:
        - name: Obtener soporte técnico para Azure AD
          href: ../fundamentals/active-directory-troubleshooting-support-howto.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
- name: Referencia
  items:
    - name: Roles con privilegios mínimos por tarea
      href: delegate-by-task.md
    - name: "Documentación de roles de Microsoft\_365"
      href: m365-workload-docs.md
    - name: Graph API
      href: /graph/api/resources/azure-ad-overview?view=graph-rest-1.0
    - name: CLI de Azure AD
      href: /cli/azure/ad
    - name: Azure AD PowerShell for Graph
      href: /powershell/azure/active-directory/install-adv2?view=azureadps-2.0
    - name: Límites de servicio de Azure AD
      href: ../enterprise-users/directory-service-limits-restrictions.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context